---
layout: post
title: '에러 핸들링을 위한 try와 catch'
author: 'Nostrss'
comments: true
tags: javascript
excerpt_separator:
sticky:
hidden:
---

## try... catch

[try catch MDN문서 보기](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Statements/try...catch)

`try`와 `catch`는 `에러핸들링`을 위해 자주 사용되는 문법이다. 

아무리 경력이 오래된 개발자라고 해도 에러는 언제든 발생할 수 있다. 그래서 에러가 발생하는 경우 프로그램이 죽지않도록 하고 에러가 발생했을때 실행될 코드를 선언해두기 위해 사용한다.

## 문법
```javascript
try {
  try_statements
}
[catch (exception_var) { 
  catch_statements //try 블록에서 예외가 발생했을 때 실행될 선언들
}]
[finally {
  finally_statements // 예외 발생 여부와 상관없이 실행된다.
}]
```

## try 선언의 구성

`try 선언의 구성`은 아래와 같다.

>1. try...catch
>2. try...finally
>3. try...catch...finally

- `catch` 블록은 `try` 블록 안에서 예외가 발생(throw)하는 경우 무엇을 할지 명시하는 코드이다. 
- `try` 블록내의 명령문이 예외를 throw 하면 제어가 `catch` 블록으로 이동하게 된다. 
- `try` 블록에 예외가 발생하지 않으면 `catch` 블록을 건너뛰게 된다.
- `finally` 블록은 예외가 발생했는지에 관계없이 항상 실행된다.
